import { AuthProvider } from "@/auth/context/jwt/auth-provider";
import { SidebarProvider } from "@/components/context";
import DashboardClientWrapper from "@/layouts/dashboard/wrapper";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <SidebarProvider>
            <DashboardClientWrapper>
              {children}
            </DashboardClientWrapper>
          </SidebarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
